### ISSUE TITLE
Non-bridging mapping?

### ISSUE THREAD

**Issue by alwhaley** [mstpd/mstpd#109]
I didn't see any documentation for this project so perhaps it's easiest to just ask.

I'd like to run this on an edge linux box (I don't run any linux bridges) and tell mstpd to pretend it's on a switch, and have it listen for and take in the spanning tree, as a way to map my network.  There are quite a few switches (mostly cisco sg300 and sg350x) in my network here in-house and it's getting hard to keep track of.

I think my understanding of STP and RSTP is that this is easily possibly in theory, but I don't know if this daemon can be made to do it.  

Before wading in knee deep in the source code and struggling to figure it out, I thought I would just ask if this software can do that, or be modified to do that, and ask if there is documentation; maybe I just missed it.

thanks
Al

**Comment by commodo** [comment]
I don't think STP/RSTP can be used to do what you want (i.e. map the network or keep track of switches).
SNMP may be a better option.

STP and RSTP [even though the name of the protocol is a bit misleading], can be used mostly to just detect if a loop exists and based on priority, block a port to prevent broadcasts from storming the network.... and that's it.
Well, you can also use this mechanism to add some redundancy; when part of the network shuts down, STP will unblock the port. since the [previously detected] loop has gone away. 

Nodes in an STP tree typically negotiate who is higher on the tree, but they don't know further than their direct nodes and the ID/priority of the root bridge.

**Comment by commodo** [comment]
I think this can be closed.

If there are any more questions here, we can re-open.
