### ISSUE TITLE
Detect __LIBC_HAS_VERSIONSORT__ during configure stage

### ISSUE THREAD

**Issue by dvitas** [mstpd/mstpd#11]
Currently this define is always defined, but it is there not without a reason, obviously there were a system where libc lacked the versionsort function. As we have now the real configure stage, it is only natural to really detect if libc has versionsort during this stage.

Not of the highest priority though. Also it would be good to check the detection on the real system with this kind of legacy libc.

**Comment by commodo** [comment]
if no objections, i'll try to implement this

**Comment by commodo** [comment]
according to glibc's changelog ([this older one](https://sourceware.org/git/?p=glibc.git;a=blob;f=ChangeLog.8;h=52b85a627091757f17056be0ff340e3e305b0cf1;hb=HEAD#l1113) ), versionsort should be in glibc since 1998 (or so)

uClibc implements it: https://git.uclibc.org/uClibc/tree/libc/misc/dirent/versionsort.c
musl libc implements it: https://git.musl-libc.org/cgit/musl/tree/src/dirent/versionsort.c

@dvitas : any recollection about why it was added here https://github.com/mstpd/mstpd/commit/1e16013cc061f64fe4793290d5e17381dc7b84c6 ?
maybe just `_GNU_SOURCE ` being defined is sufficient to have this enabled

so, we could just remove that define and stick to `versionsort` directly ?

**Comment by commodo** [comment]
i'm wondering if the case is some old Solaris systems;
if that's the case, would still we want to address that case ?

**Comment by dvitas** [comment]
If I recall it correctly it was some legacy embedded system using really old uClibc.
I think you are right and we can drop this define and use versionsort unconditionally and fix it only if it is broken for some user of mstpd.
"don't fix it if it's not broken"
