### ISSUE TITLE
Check for ifupdown in Makefile fails on cross compile

### ISSUE THREAD

**Issue by AEberleMW** [mstpd/mstpd#126]
Hi,

When cross-compiling mstpd (e.g. with [Yocto Project](https://www.yoctoproject.org)) the installation check in 
https://github.com/mstpd/mstpd/blob/f55f783610e651494736046605632056c99a61a0/Makefile.am#L87-L94
could fail, if the host system does not have `ifupdown` installed.

This especially happens when I run the build inside a container which only has a minimal set of tools and ifupdown is missing.

How could I handle this? Could you explain what the intention of this check is? Why do you check for `$(sysconfdir)/network/if-pre-up.d` and then create it in `$(etcdest)/network/if-pre-up.d`?

Thanks,
Marco

**Comment by commodo** [comment]
apologies for the slow response;
this project isn't really high-up on my todo-list;
but i still try to keep it working as best as i can

hmm; this was introduced via 1b1d9a64

the initial version of `Makefile.am` had:
```
	if [ -d $(etcdir)/network/if-pre-up.d ] ; then ln -sf $(mstpdir)/ifupdown.sh $(etcdir)/network/if-pre-up.d/mstpctl ; fi
	if [ -d $(etcdir)/network/if-post-down.d ] ; then ln -sf $(mstpdir)/ifupdown.sh $(etcdir)/network/if-post-down.d/mstpctl ; fi
```

which looks a little saner;

I wonder if @PaulSD wants to pitch-in?

If not, I guess we could revert/fix it;
i can try to make some tests these days;

**Comment by PaulSD** [comment]
Why does this fail on your system?  If ifupdown is not installed, then `$(sysconfdir)/network/if-pre-up.d` should not exist, and it should simply skip this without failing...

The problem that this code is trying to solve is:
When building a Debian package, the target/installation directory of the `make` command is a temporary path, not the real system.  In other words, $(etcdest) is something like `<current working directory>/debian/.target/etc/`.
So, the original code was checking for the existence of `$(etcdest)/network/if-post-down.d`, which will never exist when building a Debian package since that path is under a temporary directory.  Hence the symlink was never created when building a Debian package.
The current code instead checks `$(sysconfdir)/network/if-pre-up.d`, which should be the real `/etc/network/if-pre-up.d`.  If that exists, then we assume that ifupdown is installed and create the relevant path in the temporary target/installation directory, then create the symlink within it.  If ifupdown is not installed, then we should skip all of this.

**Comment by commodo** [comment]
@PaulSD 
from my personal (and limited experience with Yocto (and I've not tried anything yet here), is that Yocto does a lot of fancy moving around of folders which can expose some weird issues or inconsistencies with the build-rules;

for one thing, source files are in one folder, C object files get compiled in another folder (prefix), and output is in some other folder;
so, Yocto seems to stretch the robustness of Makefile usage or Makefile correctness;
and this is mostly because of cross-compilation, and prefix-ing or chroot-ing;

particularly in this case, i am curios of the value of `$(sysconfdir)`, whether (in Yocto context) it's `${your_local_yocto_build_folder}/etc/network/if-pre-up.d` or just `/etc/network/if-pre-up.d` (without any prefix)

or, it could be that `$(etcdest)` is not ok; and maybe @AEberleMW is pointing to an issue in the code, but maybe it's not with the `if [ -d $(sysconfdir)/network/if-pre-up.d ]; then` check;

i'm wondering if it would be more correct to do:
```
        if [ -d $(sysconfdir)/network/if-pre-up.d ]; then \
          $(MKDIR_P) $(etcdest)/network/if-pre-up.d ; \
          ln -sf $(utilsexecdir)/ifupdown.sh $(sysconfdir)/network/if-pre-up.d/mstpctl ; \
        fi
```
i.e.  `ln -sf $(mstpdir)/ifupdown.sh $(etcdir)/network/if-post-down.d/mstpctl `  -> ` ln -sf $(utilsexecdir)/ifupdown.sh $(sysconfdir)/network/if-pre-up.d/mstpctl ;`

**Comment by konradgraefe** [comment]
The problem occurs when the build host is not same as the target host and the target host has ifupdown but the build host doesn‘t.

This is the typical scenario when cross-compiling (e.g. with Yocto) but also applies when building and distributing Debian packages.

**Comment by PaulSD** [comment]
@commodo I don't think `$(sysconfdir)` can be used in the target of the `ln` command like that, as it would cause the symlink to be created in the real /etc/ of the build system when building a Debian package, instead of creating the symlink in the Debian target directory.

@konradgraefe  Oh.  I see.  That makes things much more complicated...
A few somewhat disjointed thoughts:
* ifupdown only exists on Debian distros, so those files can be excluded when building for other distros.
* When building Debian packages, it won't hurt to include the ifupdown files even if the target system won't have ifupdown installed and therefore won't use them.
* So, one option is to do some sort of Distro detection in the Makefile instead of doing the ifupdown directory detection.  (Although, this wouldn't work for cross-compilation between distros.)
* Another option is to add a make parameter or environment variable that can be set/checked instead of doing the ifupdown directory detection.
* Another option is to move the symlink creation to the Debian section of the Makefile so that it only runs when building a Debian package.
* Another option is to add a postinst script to the Debian package which creates the symlink if ifupdown exists on the target system at install time.  (But this wouldn't work right if ifupdown is installed after mstpd.)
At first glance, the third option seems like the best one (unconditionally create the symlink, but only when building a Debian package).  However, it doesn't sound like that would work for Yocto?  Maybe the second option is necessary for Yocto?

**Comment by commodo** [comment]
Yocto can be used to create Debian-like systems (for embedded devices), so doing a detection for a Debian system would be tricky as it can yield a true result even when it's not a "real" Debian system.

Unconditionally creating the symlink is not a bad idea either.
It adds a filethat won't be used if ifupdown is not present and that's that.

I think a `configure --disable-ifupdown-scripts` would also be a good middle-ground.

Or maybe a `configure --with-ifupdown-dir=<path>` which would default `$(etcdest)/network/if-pre-up.d` and take a `no` argument.
If the value is not `no`, the directory gets created and symlink installed.
This would fix the build in this report, and also allows the option to remove this symlink if desired.

Thoughts?

**Comment by konradgraefe** [comment]
Okay, I understand the situation is more complex than we initially thought. Please note that while we prefer an upstream solution we can easily patch the `Makefile.am` in our Yocto recipe to always install those scripts and we're good. So if fixing our edge case takes up a lot of developer time it might not be worth it.

> from my personal (and limited experience with Yocto (and I've not tried anything yet here), is that Yocto does a lot of fancy moving around of folders which can expose some weird issues or inconsistencies with the build-rules;
> 
> for one thing, source files are in one folder, C object files get compiled in another folder (prefix), and output is in some other folder;
> so, Yocto seems to stretch the robustness of Makefile usage or Makefile correctness;
> and this is mostly because of cross-compilation, and prefix-ing or chroot-ing;

Yocto only uses standard autotools features for that.

> 
> particularly in this case, i am curios of the value of `$(sysconfdir)`, whether (in Yocto context) it's `${your_local_yocto_build_folder}/etc/network/if-pre-up.d` or just `/etc/network/if-pre-up.d` (without any prefix)

The value of `$(sysconfdir)` is `/etc`. This is what is used during runtime. When it is used by the build system it points to the files of the build host. THis is considered an error as the content of a package should never depend on anything outside the Yocto environment.

> 
> or, it could be that `$(etcdest)` is not ok; and maybe @AEberleMW is pointing to an issue in the code, but maybe it's not with the `if [ -d $(sysconfdir)/network/if-pre-up.d ]; then` check;

`$(etcdest)` points to the installastion directory of the package (in our case `/home/user/yocto/build/tmp/work/armv5e-poky-linux-gnueabi/mstpd/0.0.8+gitAUTOINC+5371177386-r0/image/etc/network/if-pre-up.d`). So this is what should be used by the build system. (Obviously it does not work to detect if `ifupdown` is installed.)

> Unconditionally creating the symlink is not a bad idea either.
> It adds a filethat won't be used if ifupdown is not present and that's that.
> 
> I think a `configure --disable-ifupdown-scripts` would also be a good middle-ground.

Those are the two options I had in my mind, too. For me a `configure` option is cleaner.

**Comment by AEberleMW** [comment]
@all: I have the same opinion as @konradgraefe, who is actually maintaining the mstpd package in our yocto layer.

**Comment by commodo** [comment]
> Sorry for the delayed reply: I have the same opinion as @konradgraefe, who is actually maintaining the mstpd package in our yocto layer.

yes sorry for the delay from my side as well;
i've just managed yesterday to get up-to-speed with all my other open-source work on other stuff;
it's funny that i use vacations (sometimes) to resolve some of these issues  ¯\_(ツ)_/¯
(but it is fun)

opened PR #127 
let's continue there;

**Comment by commodo** [comment]
Release https://github.com/mstpd/mstpd/releases/tag/0.1.0 has been issued.

**Comment by AEberleMW** [comment]
The fix works fine for us. Thank you all for your support!
