### ISSUE TITLE
ARP request flood

### ISSUE THREAD

**Issue by matsievskiysv** [mstpd/mstpd#133]
I'm testing STP in a simple network layout and observe an ARP request flood.
![pic](https://user-images.githubusercontent.com/26824900/165449242-d9f58e9d-dd44-4cc9-ad98-29c14c631876.png)
(Each host has `mstpd` installed.)

From my understanding of STP, in this topology one of the ports should be disabled, breaking the connection ring.

Steps to reproduce:
1. Build ([stp.dockerfile.gz](https://github.com/mstpd/mstpd/files/8569972/stp.dockerfile.gz)), import it in GNS3 and start project ([stp.gns3project.gz](https://github.com/mstpd/mstpd/files/8570049/stp.gns3project.gz))

1. Suspend all traffic between machines (from GNS3 window).
1. Shut down all IPv6 stuff for each machine (otherwise ICMPv6 packets are all over the place)
   ```bash
   for i in eth0 eth1 br0 all default; do
   sysctl net.ipv6.conf.${i}.autoconf=0
   sysctl net.ipv6.conf.${i}.dad_transmits=0
   sysctl net.ipv6.conf.${i}.disable_ipv6=1
   sysctl net.ipv6.conf.${i}.drop_unicast_in_l2_multicast=1
   sysctl net.ipv6.conf.${i}.drop_unsolicited_na=1
   sysctl net.ipv6.conf.${i}.ignore_routes_with_linkdown=1
   sysctl net.ipv6.conf.${i}.mldv1_unsolicited_report_interval=0
   sysctl net.ipv6.conf.${i}.mldv2_unsolicited_report_interval=0
   sysctl net.ipv6.conf.${i}.router_probe_interval=0
   sysctl net.ipv6.conf.${i}.forwarding=0
   sysctl net.ipv6.conf.${i}.accept_ra=0
   sysctl net.ipv6.conf.${i}.accept_ra_defrtr=0
   sysctl net.ipv6.conf.${i}.accept_ra_mtu=0
   sysctl net.ipv6.conf.${i}.accept_ra_pinfo=0
   sysctl net.ipv6.conf.${i}.accept_ra_rtr_pref=0
   sysctl net.ipv6.conf.${i}.accept_redirects=0
   sysctl net.ipv6.conf.${i}.router_solicitations=0
   done
   sysctl net.ipv6.icmp.echo_ignore_all=1
   ```
1. Bring up bridge interfaces and start STP
   ```bash
   ip link add br0 type bridge stp_state 1
   ip link set eth0 master br0
   ip link set eth1 master br0
   ip link set up br0

   /sbin/bridge-stp br0 start
   mstpctl setforcevers br0 rstp # (same behaviour for stp)
   ```
1. Resume connection and validate STP root  and port states
   ```bash
   mstpctl showbridge br0 designated-root
   mstpctl showportdetail br0 eth0 state
   mstpctl showportdetail br0 eth1 state
   ```
   At this point, all machines have the same `designated-root` and one of their ports is in `discarding` state.
1. Issue single ARP request
   ```
   arp-scan -x -I eth0 -s 192.168.0.1 192.168.0.2
   ```
   and observe ARP packet flood ([stp.pcapng.gz](https://github.com/mstpd/mstpd/files/8569918/stp.pcapng.gz)).

**Comment by matsievskiysv** [comment]
I've repeated these steps with QEMU virtual machines instead of docker containers and everything worked. Seems that each router has to run its own kernel.

**Comment by commodo** [comment]
Hey,

Apologies for the slow reply.

I barely get to do anything these days.

The pcap file isn't sufficiently large enough to see how much flooding is going on).

Just to kind of provide some context (from my experience with STP), whenever you run into a flood of packets (broadcast flood or whatever), STP will not be very useful, because BPDU packets will not have room to be sent.

Even with some HW chips, sometimes a broadcast flood would start before it can send any BPDUs, and the flood can take up all the bandwidth; especially broadcasts to MAC address FF:FF:FF:FF:FF:FF (even ARP has some broadcasts like this).

In that case, STP becomes useless, and the only way to fix/address it is to try to enable some broadcast-storm limiting functionality. Some HW switches can be configured to limit the rate of broadcasts (to FF:FF:FF:FF:FF:FF) ; in reality, I think this should be done as a default behavior everywhere, because any broadcast storm will bring your network down, especially once it gets echo-ed/propagated by other devices on the network.

**Comment by matsievskiysv** [comment]
> would start before it can send any BPDUs

I don't think it's the case. ARP flood was initiated only after making sure that one port was in `discarding` state. I don't know the internals of the program, but I suspect that kernel treats docker network interfaces differently. In any case, QEMU based setup worked fine and there's no point investigating problems with docker any further.
