### ISSUE TITLE
BPDU broadcasted on embedded OpenWRT platform with switch

### ISSUE THREAD

**Issue by geek0007** [mstpd/mstpd#18]
My switch platform uses OPenWRT cc 15.05.1

I compiled RSTP from which MSTP forked.

I found BPDU are broadcasted on all ports of LAN.

LAN bridge br-lan => eth0.3 eth0.4 eth0.5 eth0.6
WAN bridge br-wan => eth0.2

switch setting use port based VLAN but CPU port use tagged VLAN.

LAN port are miss-configured by switch connected to other ports.

so question is how kernel send per port BPDU to switch and switch also understand it ?

**Comment by commodo** [comment]
On OpenWrt, a lot of switches show up as eth0 (single interface), rather than each port having it's own interface (eth0 == port1, eth1== port2, etc).

And swconfig is used to control the switch chip.
mstpd requires per-port control ; i.e. the ability to send packets on a single physical port ; and on OpenWrt the eth0 corresponding to the entire switch, means that if you send broadcast/multicast packet, it gets sent out on all ports.

So, it's a bit hard to use mstpd (at the moment) on OpenWrt and such setups.

One way to do it is to make that swconfig/switch driver expose some per-port interfaces in linux.
Another is DSA or switchdev (from linux kernel). But I don't know exactly about that.

All variants are a bit of work to do ; so, some time will take to make something work.

One question is: what switch chip are you running OpenWrt on ?

**Comment by vivien** [comment]
That is correct.

Some chips are "dumb" (i.e. realtek rtl8366s), which means you have no way to target a specific port or identify from which port a frame comes from. Linux doesn't support such switch because there is no value in creating a net interface per port. OpenWRT supports them with its out-of-tree swconfig framework.

Others chips are "smarter" (e.g. Broadcom B53, Marvell 88E6060, 88E6352, etc.). They understand a proprietary header in the frame used to identify the switch/port the frame comes from/should be sent to. Most of these switches are supported by the DSA framework in Linux.

In OpenWRT, some platforms have moved to using DSA for managed switches like 88E6060 (`grep -i` to see), others still use swconfig. As correctly pointed out by @commodo, mstpd can only work on standard Linux network interfaces, thus DSA instances.

For the details: DSA means Distributed Switch Architecture which is a Marvell term. But this term is used by Linux to describe this generic class of switches. switchdev is a stateless API to bind bridge operations, thus the core of DSA uses switchdev.

**Comment by geek0007** [comment]
I use MT7621A mediatek SoC chipset which has MT7530 GSW chip but it has almost no support from chip manufacturer, not even docs.

Yes, as I know STP need per port interface to control so I changed openwrt default network setting and got eth0.3 eth0.4 eth0.5 eth0.6 for per port and bridged then in br-lan.
 Also I got bridge for wan interface i.e br-wan with eth0.2 interfaces.

br-lan => eth0.3 eth0.4 eth0.5 eth0.6        MAC1
br-wan => eth0.2                                       MAC2

As I know Linux interface is up-to OSI Layer 3 and layer 2 routing only use MAC but for RSTP/MSTP
LAN interfaces still have same MAC and Linux can not help in routing this RSTP BPDU packet to specific port according to RSTP port ID.
Even switch hardware also use MAC and then other tagging filtering to route on layer 2.
With same MAC BPDU packets need some port specific tagging which switch understands.

Is this understanding is correct ??
I have not found any document with all this details so I am still just exploring.

**Comment by commodo** [comment]
> Yes, as I know STP need per port interface to control so I changed OpenWRT default network setting and got eth0.3 eth0.4 eth0.5 eth0.6 for per port and bridged them in br-lan.
Also, I got bridge for wan interface i.e br-wan with eth0.2 interfaces.

eth0.3 eth0.4 eth0.5 eth0.6 are not physical ports perse ; they are just VLAN ports to the same eth0 which is the switch [usually in OpenWrt];
but I think, from mstpd's point of view, this approach should work as well

> As I know Linux interface is up-to OSI Layer 3 and layer 2 routing only use MAC but for RSTP/MSTP
LAN interfaces still have same MAC and Linux can not help in routing this RSTP BPDU packet to specific port according to RSTP port ID.
[ Note: I would avoid the term routing for MAC ; it makes me think of GW routing. ]
I don't think the MAC address matters much in the case of `mstpd` ; mstpd work\s on Linux bridges [by default], and in a bridge, all interfaces inherit the bridge's MAC address.

In any case, I am having a bit of trouble following what you are saying.
Maybe that's why I deferred answering.

So let me try to summarize here a bit:
* If you have a simple ASIC switch, that shows up as `eth0` and you configure VLANs for each LAN port:
  * you will get an interface per-port (eth0.3, eth0.4, etc)
  * you will lose any HW switching ; since each port is in different VLAN, the ASIC will not forward traffic between ports
* However, you can:
  * create a SW bridge on those ports, like you are doing `br-lan => eth0.3 eth0.4 eth0.5 eth0.6 MAC1`
  * the CPU will have more work to do, because the HW switch ASIC will no longer forward packets between LAN ports
  * you can run `mstpd` in this screnario, but it offers little benefit, because the performance will be limited to what the CPU can handle to forward traffic between LAN ports

I hope this helps.
Sorry for taking too long to answer.
