### ISSUE TITLE
A question about Bridge Priority

### ISSUE THREAD

**Issue by w-silence-w** [mstpd/mstpd#52]
**in this function at mstp.c, bridge_priority range is  0–240 in steps of 16, as shown in the figure:**

![image](https://user-images.githubusercontent.com/30229190/33005265-fee0d610-cdff-11e7-9cbf-11e2fcaa86f5.png)

**but in 802.1D 17.14 , bridge_priority range is 0–61440 in steps of 4096, as shown in the figure:**

![image](https://user-images.githubusercontent.com/30229190/33005404-a0f49dec-ce00-11e7-812b-8e8b7ff3241c.png)

**I'm not sure whether my understanding is correct.Please help me， thanks！**

**Comment by w-silence-w** [comment]
**in my opinion,

`valuePri = bridge_priority << 4; 
`

Should be changed to

`valuePri = bridge_priority << 12;`**

**Comment by commodo** [comment]
hey

yes, you're right about  `valuePri = bridge_priority << 12;`  but, what's a happening here is a bit of an optimization;
shifting 12 bits is a bit more expensive than shifting 4

and valuePri is an 8 bit value, so, it makes no sense to shift it more than 8 bits;
if you check `mstp.h` there's 
```
#define SET_PRIORITY_IN_IDENTIFIER(pri, id) do{ \
    __u8 *first_octet = (__u8 *)(&(id));        \
    *first_octet &= 0x0F;                       \ 
    *first_octet |= (pri) & 0xF0;               \
    }while(0)
```

which basically sets the `valuePri` bits only to the first byte ; 
so,   `valuePri = bridge_priority << 4; + 8 bits` [from the first byte] is 12

on the wire, the bridge priority shows up correctly, otherwise it's likely other daemons would not work with `mstpd`

**Comment by w-silence-w** [comment]
@commodo 
get it, thank you very much!
