### ISSUE TITLE
Example/Pseudo code for MST in drivers

### ISSUE THREAD

**Issue by Platin21** [mstpd/mstpd#83]
Hello, 

We are currently trying to implement the MSTP functionality 
for our driver now it's a bit unclear how the entire setup is done
and the example Broadcom is not really fully implemented i suspected 
this because of some NDA information? 

I suspect it's do able to make it possible to have arbitrary mst id's that do
not correspond to the database index. I mean i can see how this could be
done in the driver deps. (As such a thing is currently a requirement for us)

Anyways a pseudo example how to would have been great.

**Comment by commodo** [comment]
So, straight-off-the-bat MSTP does not work well with all switches. I believe it works fine with Cisco, but some HP or Dell switches misbehave with mstpd's logic [under certain setups].
Most people seem to use mstpd with RSTP or PVRSTP.
Even Cumulus Networks [who have forked & publicized some patches for mstpd] uses RSTP & PVRSTP, which probably means that MSTP is not that widely used [even though in theory it looks like a good protocol from an evolutionary stand-point].
It did not seem to get much adoption.

I don't have any source code to recommend for MSTP with Broadcom [other than what's in this repo], and that was created by @dvitas a while back.
Those bits of code seem to use Broadcom's SDK, which is really NDA protected.

I got it running a while back on [OpenWrt with the b53 driver](https://github.com/openwrt/openwrt/tree/master/target/linux/generic/files/drivers/net/phy/b53).
The driver was patched internally, and many patches didn't make it upstream though I tried [review efforts were slow at the time in OpenWrt]. You can [check out some of them here](http://patchwork.ozlabs.org/project/openwrt/list/?series=&submitter=65503&state=*&q=b53&archive=both&delegate=).

mstpd also required some changes to get it running properly with some HW support.
The b53 driver is interesting, because it's good enough to develop mstpd around MSTP; it has some good HW support for this protocol [and storing MST IDs and stuff in HW].

The b53 driver is also present in upstream Linux [in a different form] and I think @vivien had something running with DSA and/or switchdev at some point.
Maybe he could point you in some directions.

To conclude: mstpd will get you started with MSTP, but it's not yet production worthy/ready enough. So, if you get it running and find issues, we welcome patches [I know this is typically said in all OS projects].

Thanks
Alex

**Comment by Platin21** [comment]
Yeah we are interested in both actually MSTP and RSTP. Our switch doesn’t have hardware MSTI’s but that’s easy enough todo in software. 

Sure we might get a test suite going for MSTP so that we can look where it might deviate. As we want to actively use it as PVSTP is more or less cisco only and we do have some switches wich don’t support that. 

That it works with ciscos is already a great thing as our customers use them. 
We might gather some results also with hirschmann and marvell.

**Comment by Platin21** [comment]
@commodo Any examples for the driver_deps.c?
I suspect currently that driver_set_new_state is for setting the individual ports to there states inside a MSTI?

I don't really get what driver_create_port and delete should do?
Same for create_bridge and delete_bridge is this just the initial setup?
E.g creation of vlans and such? as there is no specific hardware state that needs to be set in order for the switch to make it possible to use the ports attached to the bridge. 
And driver_create_msti and delete are then for selecting subranges on the ports which should belong to a msti i suspect?

**Comment by mg964** [comment]
> I suspect currently that driver_set_new_state is for setting the individual ports to there states inside a MSTI?

Yes, push down the MSTI and associated state to your "dataplane". 
```
    port_t *prt = ptp->port;
    bridge_t *br = prt->bridge;

    if (br->bridgeEnabled &&
        (br->ForceProtocolVersion == protoMSTP) &&
        (ptp->MSTID != 0))
        vrouter_set_state(br, prt, __be16_to_cpu(ptp->MSTID),
                          new_state, false);

    return new_state;
```
Where "vrouter_set_state()" is some home-grown ZMQ-based code used to talk to the dataplane element.   

> I don't really get what driver_create_port and delete should do?
> Same for create_bridge and delete_bridge is this just the initial setup?

For driver_create_bridge() driver_create_port(), driver_delete_bridge() I didn't do anything with these hooks. For driver_delete_port() I added some sanity code to ensure any/all MSTI configuration was removed from the dataplane (MSTI is BR_STATE_DISABLED).

The only other hook that I populated is driver_flush_all_fids() - clear out mac addresses from the dataplane.

**Comment by Platin21** [comment]
@mg964 why do you delete all the msti configurations if a port get's deleted?
I thought about just deleting that config for that particular port is this wrong?

**Comment by mg964** [comment]
> @mg964 why do you delete all the msti configurations if a port get's deleted?
I thought about just deleting that config for that particular port is this wrong?

Sorry poor phrasing, I meant that for the given port, ensure that each MSTI is DISABLED. Its really a bit of belt-and-braces associated with our dataplane.

**Comment by Platin21** [comment]
@mg964 in which state do you set this port then? 
I did just remove it from the V-Lan and set the state to disabled. 
Same happens when i delete a msti. 

Another thing is why is the MSTID on per_tree_port_t a __be16 type?
That is big endian and 16bit? ist the id everywhere a big endian type?

**Comment by mg964** [comment]
> Another thing is why is the MSTID on per_tree_port_t a __be16 type?
That is big endian and 16bit? ist the id everywhere a big endian type?

16-bits because the value range is 0..4094. Its kept as a __be16 (big-endian/network-order) so that it can be written directly into generated packets rather than having to do the (possible) conversion from native (host) format every time.

I guess these days the "cost" of conversion is probably not measurable.

**Comment by Platin21** [comment]
Ahh so it's just a thing for the speed.

@mg964 
Other question how do i check which vlans a particular fid has do i need to iterate over the entire array of vid's to get there fid's?

**Comment by mg964** [comment]
> Other question how do i check which vlans a particular fid has do i need to iterate over the entire array of vid's to get there fid's?

Looks like you would need to walk the VLAN ID range. See MSTP_IN_set_all_vids2fids() and MSTP_IN_set_fid2mstid() for some examples.

**Comment by Platin21** [comment]
Do the port numbers start with zero?
As we currently index by one.

**Comment by mg964** [comment]
AFAIK the kernel (not mstpd) generates port numbers from 1. Why do you care?

**Comment by Platin21** [comment]
Ahh else the ports wouldn't have a relation to the real ports. 
Other thing i now have the following:
> Kernel interface to our switch for the vtu: `fid 0 vid 12 port 1 forwarding set`
Same for the atu: 
> Kernel interface to our switch for the atu: `flush port 1 db 1`

I'm a bit unsure what dirver_flush_all_fids should do as it gets a per_tree_port.
Currently i go over all fids that have the mstid in it and flush the port in that db.
Is that meant only for the ATU?

For the function driver_set_new_state i go through all fid's with the mstid and through all vlans with the fid when i set the state of a per tree port. I suspect i need to check the Protocol Version and if the mstid ist zero?
While zero will be always the IST.

**Comment by Platin21** [comment]
As mentioned on the beginning a pseudo implementation of the driver_deps.c would have helped a lot.

**Comment by Platin21** [comment]
Anyways thanks for the help. 
I will commit some example pseudo example code so that it’s easier for people that don’t have msti hardware support but only PVSTP

**Comment by mg964** [comment]
Now that its been published, you can take a look at the "stub" driver patch we use for MSTP with DANOS (Vyatta):
https://github.com/danos/mstpd/tree/master/debian/patches
Its very specific to our control/data plane objects and some "distance" from any hardware, but it may be of some use.
Cheers,
Mark

**Comment by Platin21** [comment]
Do you guys do any testing on them e.g conformance tests?

**Comment by mg964** [comment]
Not aware of anything that specific. Tends to be higher-level functional testing.

**Comment by Platin21** [comment]
How does the msptd actually say which port belongs to a tree?

**Comment by mg964** [comment]
If you are trying to see which ports belong to which MSTP instance (msti), then its a combination of "showmstilist"  & "showtreeport". For a given port, something like:

mstilist = mstpctl showmstilist <bridge>
foreach msti in mstilist:
    mstpctl showtreeport <bridge> <port> <msti>
    if out is "Couldn't find MSTI with ID"
        continue
Does that help?




and then, for each port, issue "showtreeport <bridge> <port> <msti>".

**Comment by Platin21** [comment]
Ahh sure but what i actually meant was how can i add a port or remove a port from a msti.
E.g i want to have Port X not being a member of Msti Y.

**Comment by mg964** [comment]
Try using settreeportprio and/or settreeportcost, that should allow you to control which port is assigned to a particular msti.

**Comment by Platin21** [comment]
The would still be in that msti. Treeportcost and Treeportprio don't change anything about that the port is member of a particular msti. E.g i want to have sort of a bridge device that has both msti's and i want to have some which don't have both.

**Comment by Platin21** [comment]
So the mstpd can only be used to bridge over multiple msti's but not really if you don't want it to have all msti's.
